alias cls='clear'
alias qfind='~/Documents/commandCenter/qfind'
alias dfind='~/Documents/commandCenter/dfind'
alias cdls='source ~/Documents/commandCenter/cdls'
alias cp='cp -rv'
alias rm='rm -rv'
alias ls='ls -l -t --color=auto'
