alias cdls='source ~/Documents/commandCenter/cdls'
alias cls='clear'
alias cp='cp -rv'
alias dfind='~/Documents/commandCenter/dfind'
alias ls='ls -l -t --color=auto'
alias mv='mv -v'
alias qfind='~/Documents/commandCenter/qfind'
alias rm='rm -rv'
