alias cdls='source $HOME/CommandCenter/cdls'
alias cls='clear'
alias cp='cp -rv'
alias dfind='$HOME/CommandCenter/dfind'
alias ls='ls -l -t --color=auto'
alias lsg='ls --group-directories-first'
alias mv='mv -v'
alias qfind='$HOME/CommandCenter/qfind'
alias rm='rm -rfv'
